"""keywords

Revision ID: 2a55230dd085
Revises: c3c93c5e7361
Create Date: 2026-10-05 23:01:30.098504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a55230dd085'
down_revision: Union[str, Sequence[str], None] = 'c3c93c5e7361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('search_words', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', text)", persisted=True), nullable=False))
    op.create_index('ix_document_chunks_search_words', 'document_chunks', ['search_words'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_chunks_search_words', table_name='document_chunks', postgresql_using='gin')
    op.drop_column('document_chunks', 'search_words')
    # ### end Alembic commands ###
