"""pages

Revision ID: 9ba250902062
Revises: efc2b3217311
Create Date: 2026-10-02 11:30:37.568569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba250902062'
down_revision: Union[str, Sequence[str], None] = 'efc2b3217311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_pages',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'page_number')
    )
    op.add_column('documents', sa.Column('status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('documents', sa.Column('error', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'error')
    op.drop_column('documents', 'status')
    op.drop_table('document_pages')
    # ### end Alembic commands ###
