"""source

Revision ID: d51d2edbc179
Revises: 36eb4e9b4b91
Create Date: 2026-10-03 13:08:52.295597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd51d2edbc179'
down_revision: Union[str, Sequence[str], None] = '36eb4e9b4b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_parts', sa.Column('source', sa.String(length=10), server_default='text', nullable=False))
    op.add_column('documents', sa.Column('ocr_part_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'ocr_part_count')
    op.drop_column('document_parts', 'source')
    # ### end Alembic commands ###
